# Generated by Django 3.0.4 on 2020-07-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glazingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='works_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('Images', models.ImageField(default='', upload_to='glazingapp/images')),
            ],
        ),
    ]
