# Generated by Django 3.0.4 on 2020-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glazingapp', '0004_auto_20200718_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='works_model',
            name='status',
            field=models.CharField(default='', max_length=15),
        ),
    ]
